# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculadora.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61lculadora.proto\x12\x04\x63\x61lc\"*\n\x10OperacionRequest\x12\n\n\x02n1\x18\x01 \x01(\x01\x12\n\n\x02n2\x18\x02 \x01(\x01\"#\n\x11OperacionResponse\x12\x0e\n\x06result\x18\x01 \x01(\x01\x32\xf8\x01\n\x12\x43\x61lculadoraService\x12\x37\n\x04suma\x12\x16.calc.OperacionRequest\x1a\x17.calc.OperacionResponse\x12\x38\n\x05resta\x12\x16.calc.OperacionRequest\x1a\x17.calc.OperacionResponse\x12\x37\n\x04mult\x12\x16.calc.OperacionRequest\x1a\x17.calc.OperacionResponse\x12\x36\n\x03\x64iv\x12\x16.calc.OperacionRequest\x1a\x17.calc.OperacionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculadora_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OPERACIONREQUEST']._serialized_start=27
  _globals['_OPERACIONREQUEST']._serialized_end=69
  _globals['_OPERACIONRESPONSE']._serialized_start=71
  _globals['_OPERACIONRESPONSE']._serialized_end=106
  _globals['_CALCULADORASERVICE']._serialized_start=109
  _globals['_CALCULADORASERVICE']._serialized_end=357
# @@protoc_insertion_point(module_scope)
